services:

  fluentd:
    container_name: llm-fluentd
    build:
      context: ./fluentd
    volumes:
      - ./fluentd/etc:/fluentd/etc:ro
      - ./fluentd/log:/fluentd/log
      - ./datasets:/datasets:ro
      - ./fluentd/scripts:/fluentd/scripts
    env_file:
      - .env
    command: >
      bash -c "nohup /fluentd/scripts/filemonitoring_fluentd.sh & fluentd -c /fluentd/etc/fluent.conf"
    networks:
      - app_network
    restart: on-failure

  couchdb:
    container_name: llm-couchdb
    build:
      context: ./couchdb
    ports:
      - "5984:5984"
    env_file:
      - .env
    volumes:
      - couchdb-data:/opt/couchdb/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/_up"]
      interval: 10s
      retries: 5
    restart: always

  spark:
    container_name: llm-spark
    build:
      context: ./spark
    ports:
      - "8080:8080"
      - "4040:4040"
    volumes:
      - ./spark:/spark
      - ./datasets:/datasets
    env_file:
      - .env
    networks:
      - app_network
    restart: on-failure

  app:
    container_name: llm-app
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./datasets:/datasets:ro
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: '4'
        reservations:
          cpus: '2'
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      onprem:
        condition: service_healthy

  onprem:
    container_name: llm-onprem
    build:
      context: ./onprem
      dockerfile: Dockerfile
    volumes:
      - ./onprem:/onprem  
      - ./datasets:/datasets
    env_file:
      - .env
    ports:
      - "5001:5001"
    networks:
      - app_network
    depends_on:
      spark:
        condition: service_started  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/status"]
      interval: 10s
      retries: 50
      start_period: 60s
    restart: always

volumes:
  couchdb-data:
    driver: local

networks:
  app_network:
    driver: bridge
