services:

  fluentd:
    container_name: llm-fluentd
    build:
      context: ./fluentd
      cache_from:
        - fluentd_cache
      args:
        BUILDKIT_INLINE_CACHE: "1"
    volumes:
      - ./fluentd/etc:/fluentd/etc:ro
      - ./fluentd/log:/fluentd/log
      - ./datasets:/datasets:ro
      - ./fluentd/scripts:/fluentd/scripts
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - FLUENTD_OPT="--log-level info"
    env_file:
      - .env
    depends_on:
      couchdb:
        condition: service_healthy
    command: >
      bash -c "nohup /fluentd/scripts/filemonitoring_fluentd.sh & fluentd -c /fluentd/etc/fluent.conf"
    networks:
      - app_network
    restart: on-failure

  couchdb:
    container_name: llm-couchdb
    build:
      context: ./couchdb
      cache_from:
        - couchdb_cache
      args:
        BUILDKIT_INLINE_CACHE: "1"
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_CLUSTER_Q=1
      - COUCHDB_CLUSTER_N=1
    volumes:
      - couchdb-data:/opt/couchdb/data
    networks:
      - app_network
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/_up"]
      interval: 10s
      retries: 5
    restart: always

  spark:
    container_name: llm-spark
    build:
      context: ./spark
      cache_from:
        - spark_cache
      args:
        BUILDKIT_INLINE_CACHE: "1"
    ports:
      - "8080:8080"
      - "4040:4040"
    volumes:
      - ./spark:/spark:ro
    depends_on:
      couchdb:
        condition: service_healthy
      app:
        condition: service_started
    env_file:
      - .env
    networks:
      - app_network
    restart: on-failure

  app:
    container_name: llm-app
    build:
      context: ./app
      dockerfile: Dockerfile
      cache_from:
        - app_cache
      args:
        BUILDKIT_INLINE_CACHE: "1"
    volumes:
      - ./datasets:/app/datasets:ro
    environment:
      - MODEL_DIR=/datasets/llm_model
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: '4'
        reservations:
          cpus: '2'
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      onprem:
        condition: service_healthy

  onprem:
    container_name: llm-onprem
    build:
      context: ./onprem
      dockerfile: Dockerfile
      cache_from:
        - onprem_cache
      args:
        BUILDKIT_INLINE_CACHE: "1"
    ports:
      - "5001:5001"
    depends_on:
      couchdb:
        condition: service_healthy
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/status"]
      interval: 10s
      retries: 5
      start_period: 10s
    restart: always

volumes:
  couchdb-data:
    driver: local

networks:
  app_network:
    driver: bridge
