services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.0
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./datasets:/datasets  # Per accedere ai file XML
    ports:
      - "5044:5044"
    depends_on:
      - arangodb
    networks:
      - backend

  arangodb:
    image: arangodb/arangodb:latest
    ports:
      - "8529:8529"
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_ROOT_PASSWORD} # Dal file .env
    volumes:
      - arangodb-data:/var/lib/arangodb3
    networks:
      - backend

  spark:
    build: ./spark
    ports:
      - "8080:8080"
    depends_on:
      - arangodb
    networks:
      - backend

  onprem:
    build:
      context: .
      dockerfile: Dockerfile.onprem
    ports:
      - "8000:8000"  
    environment:
      - MODEL_PATH=${MODEL_PATH} # Dal file .env
    volumes:
      - ./datasets/llm_models:/app/datasets/llm_models
    networks:
      - backend
    depends_on:
      - spark

volumes:
  arangodb-data:
    driver: local

networks:
  backend:
    driver: bridge
