services:
  fluentd:
    build: ./fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/etc:/fluentd/etc
      - ./fluentd/log:/fluentd/log
      - ./datasets:/datasets
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    env_file: 
      - .env
    depends_on:
      couchdb:
        condition: service_healthy
    command: ["fluentd", "-c", "/fluentd/etc/test1.conf", "-vv"]
    networks:
      - backend
    restart: on-failure

  couchdb:
    build: ./couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - couchdb-data:/opt/couchdb/data
    networks:
      - backend
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/_up"]
      interval: 10s
      retries: 5

  spark:
    build: ./spark
    ports:
      - "8080:8080"
    depends_on:
      - couchdb
    networks:
      - backend

  onprem:
    build:
      context: .
      dockerfile: Dockerfile.onprem
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH
    volumes:
      - ./datasets/llm_models:/app/datasets/llm_models
    networks:
      - backend
    depends_on:
      - spark

volumes:
  couchdb-data:
    driver: local

networks:
  backend:
    driver: bridge
