services:
  fluentd:
    container_name: llm-fluentd
    build:
      context: ./fluentd
    volumes:
      - ./fluentd/etc:/fluentd/etc:ro
      - ./fluentd/log:/fluentd/log
      - ./datasets:/datasets:ro
      - ./fluentd/scripts:/fluentd/scripts
    env_file:
      - .env
    command: >
      bash -c "nohup /fluentd/scripts/filemonitoring_fluentd.sh & fluentd -c /fluentd/etc/fluent.conf"
    networks:
      - llm_network
    restart: on-failure

  couchdb:
    container_name: llm-couchdb
    build:
      context: ./couchdb
    ports:
      - "5984:5984"
    env_file:
      - .env
    volumes:
      - couchdb-data:/opt/couchdb/data
    networks:
      - llm_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/_up"]
      interval: 10s
      retries: 5
    restart: unless-stopped

  spark:
    container_name: llm-spark
    build:
      context: ./spark
    ports:
      - "8080:8080"
      - "4040:4040"
    volumes:
      - ./spark:/spark
      - ./datasets:/datasets
    env_file:
      - .env
    networks:
      - llm_network
    restart: unless-stopped

  utils:
    container_name: llm-utils
    build:
      context: ./utils
      dockerfile: Dockerfile
    volumes:
      - ./utils:/utils
      - ./datasets:/datasets:rw
    networks:
      - llm_network
    deploy:
      resources:
        limits:
          cpus: "1"
        reservations:
          cpus: "1"
    restart: unless-stopped
    ports:
      - "5000:5000"

  onprem:
    container_name: llm-onprem
    build:
      context: ./onprem
      dockerfile: Dockerfile
    volumes:
      - ./onprem:/onprem
      - ./datasets:/datasets
    env_file:
      - .env
    ports:
      - "5001:5001"
    networks:
      - llm_network
    depends_on:
      spark:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/status"]
      interval: 10s
      retries: 50
      start_period: 60s
    restart: unless-stopped

volumes:
  couchdb-data:
    driver: local

networks:
  llm_network:
    driver: bridge
